trigger:
  branches:
    include:
      - develop

resources:
  repositories:
    - repository: devops
      type: git
      name: Devops

extends:
  template: templates/build-microservice.yml@devops
  parameters:
    appName: "coloresdevida-front"
    imageRepository: ""coloresdevida-front"
    secretFileName: ""coloresdevida-front-secret.yaml"
    deploymentType: "frontend"
    backendAppName: ""coloresdevida-backend"
    subdomain: ""coloresdevida"
