apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tuberculosis-ingress
  namespace: tuberculosis
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Optional: If you want to rewrite paths or control precedence explicitly
    # nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - tumedico.prioritech.com.co
    secretName: tuberculosis-ingress-tls
  rules:
  - host: tumedico.prioritech.com.co
    http:
      paths:
      # NUEVA RUTA: Para todas las llamadas a la API (Basado en tus imágenes)
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: tuberculosis-backend
            port:
              number: 80
      # Route for Swagger UI
      - path: /swagger-ui
        pathType: Prefix
        backend:
          service:
            name: tuberculosis-backend
            port:
              number: 80
      # Route for OpenAPI Docs (v3)
      - path: /v3/api-docs
        pathType: Prefix
        backend:
          service:
            name: tuberculosis-backend
            port:
              number: 80
      # Default route for Frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tuberculosis-frontend
            port:
              number: 80